name: emo_cap_flutter
description: Emotion-Capture Flutter Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #provider
  provider: ^6.0.5
  #다국어 처리
  flutter_localizations:
    sdk: flutter
  #앱이 종료되어도 데이터 저장 처리
  shared_preferences: ^2.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  #Http API 통신
  http: ^0.13.5
  #json 직렬화 관련
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  #json 직렬화
  build_runner: ^2.3.3
  #json 직렬화
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

