name: emo_cap_flutter
description: Emotion-Capture Flutter Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #provider
  provider: ^6.0.5
  #다국어 처리
  flutter_localizations:
    sdk: flutter
  #앱이 종료되어도 데이터 저장 처리
  shared_preferences: ^2.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  #Http API 통신
  http: ^0.13.5
  #json 직렬화 관련
  json_annotation: ^4.8.0
  # rest API 통신
  chopper: ^6.1.4
  get: ^4.6.5
  pretty_chopper_logger: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  #json 직렬화
  build_runner: ^2.3.3
  #json 직렬화
  json_serializable: ^6.6.1
  # rest API 통신
  chopper_generator: ^6.0.3

fonts:
  - family: Noto_Serif_KR
    fonts:
      - asset: assets/font/Noto_Sans_KR/static/NotoSansKR-Thin.ttf
        weight: 200
      - asset: assets/font/Noto_Sans_KR/static/NotoSansKR-ExtraLight.ttf
        weight: 300
      - asset: assets/font/Noto_Sans_KR/static/NotoSansKR-Light.ttf
        weight: 400
      - asset: assets/font/Noto_Sans_KR/static/NotoSansKR-Regular.ttf
        weight: 500
      - asset: assets/font/Noto_Sans_KR/static/NotoSansKR-Medium.ttf
        weight: 600
      - asset: assets/font/Noto_Sans_KR/static/NotoSansKR-SemiBold.ttf
        weight: 700
      - asset: assets/font/Noto_Sans_KR/static/NotoSansKR-Bold.ttf
        weight: 900

flutter:
  uses-material-design: true

